language: java
addons:
    sonarcloud:
        organization: "jramirezl-github"
        token:
            secure: o7CK3/l58rDB5yhrFlz3FBalbRdkYLFJ1nJnxc/uj1WsNAy4GvC6VwdaWw/mwjQb/HECRtp/L3iSd6i99MctyafdEnPRzHBebk+ajwdeG7EwZO68DelLyeUOBKPiBxqJ8YXT9m8I3fxGwmWOqEhzbkP2KL7X1LJGnxm3EfUocwcdSphikh5KGM1TstKBmdDBczJr72f1xDkiEjOclrcq0z7iMUe/1Pc8i4Ne6ENVxxbRwVRpQ5tkbOqav7WQToGS/RV5Key/b4Zgr/iuThT9zZPnlMrf7FJSB0XgcbQZRxwMHg1e5eiGP87fLiIk1BGVvVqEYYr8u6uLuMgy0o1+7xMVYkPogyzxhi+Jp80snnZuweFMNkD1KNwxOHbjJX1sg47NqaOIDB45xMF9GyiCqUJrgjvqiWYEdbeWq8aBwGelfshkjAfsSgsMqFLoAhRUdGWt+Cpgczs31ohZLHGP+FyFigqY+W6DVZHvSHacPhH446xtaw9effOlCGH0slh7B9FZLUJixBSuPlKHUcjQ89Il4zQFKGevUHZhdqBBwtu4vz+laXnVpyzY+PiUCg9ZwXTp6tpYDtn2fJRDB2b2pYgvki8BN/kdd/Pdp9/7V6AAfy2gA8G57sSY8JjEoMq086Rzk+OqpVLOL/cCjf+xdsCDYY10phPbMnbEHXxv0xE=
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
